version: "3.8"
services:
  catalog-service:
    image: "sagiransari/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8080