services:
  catalog-service:
    image: "catalog-service"
    container_name: "catalog-service:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001