apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: catalog-service
build:
  artifacts:
    - image: sagiransari/catalog-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=11.*
deploy:
  kubectl:
    manifests:
      - k8s/*.yml