server:
  port: 8080
  tomcat:
    connection-timeout: 5s
    threads:
      max: 100
      min-spare: 10
  error:
    include-message: always
    include-binding-errors: always
  shutdown: graceful
spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config.import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      request-connect-timeout: 5000 # 1s
      request-read-timeout: 15000 # 5s
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  profiles:
    active:
  datasource:
    username: sagir
    password: password
    url: jdbc:mysql://helllo:3306/springnative
    hikari:
      max-lifetime: 60000
      auto-commit: false
      idle-timeout: 3000
      minimum-idle: 5
      leak-detection-threshold: 240000
      maximum-pool-size: 100
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management.endpoints.web.exposure.include: refresh
springdoc:
  swagger-ui:
    path: /swagger-ui
